-- -------------------------------------------------------------
-- 
-- File Name: mhdlcoder/untitled/mul_add_pkg.vhd
-- Created: 2025-11-26 19:10:16
-- 
-- Generated by MATLAB 26.1, HDL Coder 26.1, and Simulink 26.1
-- 
-- -------------------------------------------------------------


LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

PACKAGE mul_add_pkg IS
  TYPE vector_of_std_logic_vector16 IS ARRAY (NATURAL RANGE <>) OF std_logic_vector(15 DOWNTO 0);
  TYPE vector_of_std_logic_vector135 IS ARRAY (NATURAL RANGE <>) OF std_logic_vector(134 DOWNTO 0);
  TYPE vector_of_unsigned16 IS ARRAY (NATURAL RANGE <>) OF unsigned(15 DOWNTO 0);
  TYPE vector_of_unsigned32 IS ARRAY (NATURAL RANGE <>) OF unsigned(31 DOWNTO 0);
  TYPE vector_of_unsigned33 IS ARRAY (NATURAL RANGE <>) OF unsigned(32 DOWNTO 0);
  TYPE vector_of_unsigned66 IS ARRAY (NATURAL RANGE <>) OF unsigned(65 DOWNTO 0);
  TYPE vector_of_unsigned67 IS ARRAY (NATURAL RANGE <>) OF unsigned(66 DOWNTO 0);
  TYPE vector_of_unsigned134 IS ARRAY (NATURAL RANGE <>) OF unsigned(133 DOWNTO 0);
  TYPE vector_of_unsigned135 IS ARRAY (NATURAL RANGE <>) OF unsigned(134 DOWNTO 0);
END mul_add_pkg;

