-- -------------------------------------------------------------
-- 
-- File Name: multiply/untitled/mul_add.vhd
-- Created: 2025-11-26 20:01:39
-- 
-- Generated by MATLAB 26.1, HDL Coder 26.1, and Simulink 26.1
-- 
-- 
-- -------------------------------------------------------------
-- Rate and Clocking Details
-- -------------------------------------------------------------
-- Model base rate: 1
-- Target subsystem base rate: 1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: mul_add
-- Source Path: untitled/mul_add
-- Hierarchy Level: 0
-- Model version: 1.2
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;
USE work.mul_add_pkg.ALL;

ENTITY mul_add IS
  PORT( In1                               :   IN    vector_of_std_logic_vector16(0 TO 127);  -- uint16 [128]
        Out1                              :   OUT   vector_of_std_logic_vector135(0 TO 127)  -- ufix135_En107 [128]
        );
END mul_add;


ARCHITECTURE rtl OF mul_add IS

  -- Signals
  SIGNAL In1_unsigned                     : vector_of_unsigned16(0 TO 127);  -- uint16 [128]
  SIGNAL Gain_out1                        : vector_of_unsigned32(0 TO 127);  -- ufix32_En14 [128]
  SIGNAL Add_add_cast                     : vector_of_unsigned33(0 TO 127);  -- ufix33_En14 [128]
  SIGNAL Add_add_cast_1                   : vector_of_unsigned33(0 TO 127);  -- ufix33_En14 [128]
  SIGNAL Add_out1                         : vector_of_unsigned33(0 TO 127);  -- ufix33_En14 [128]
  SIGNAL Gain1_out1                       : vector_of_unsigned66(0 TO 127);  -- ufix66_En44 [128]
  SIGNAL Add1_add_cast                    : vector_of_unsigned67(0 TO 127);  -- ufix67_En44 [128]
  SIGNAL Add1_add_cast_1                  : vector_of_unsigned67(0 TO 127);  -- ufix67_En44 [128]
  SIGNAL Add1_out1                        : vector_of_unsigned67(0 TO 127);  -- ufix67_En44 [128]
  SIGNAL Gain2_out1                       : vector_of_unsigned134(0 TO 127);  -- ufix134_En107 [128]
  SIGNAL Add2_add_cast                    : vector_of_unsigned135(0 TO 127);  -- ufix135_En107 [128]
  SIGNAL Add2_add_cast_1                  : vector_of_unsigned135(0 TO 127);  -- ufix135_En107 [128]
  SIGNAL Add2_out1                        : vector_of_unsigned135(0 TO 127);  -- ufix135_En107 [128]

BEGIN
  outputgen1: FOR k IN 0 TO 127 GENERATE
    In1_unsigned(k) <= unsigned(In1(k));
  END GENERATE;


  Gain_out1_gen: FOR t_0 IN 0 TO 127 GENERATE
    Gain_out1(t_0) <= resize(In1_unsigned(t_0) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 32);
  END GENERATE Gain_out1_gen;



  Add_out1_gen: FOR t_01 IN 0 TO 127 GENERATE
    Add_add_cast(t_01) <= resize(In1_unsigned(t_01) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 33);
    Add_add_cast_1(t_01) <= resize(Gain_out1(t_01), 33);
    Add_out1(t_01) <= Add_add_cast(t_01) + Add_add_cast_1(t_01);
  END GENERATE Add_out1_gen;



  Gain1_out1_gen: FOR t_02 IN 0 TO 127 GENERATE
    Gain1_out1(t_02) <= resize(Add_out1(t_02) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 66);
  END GENERATE Gain1_out1_gen;



  Add1_out1_gen: FOR t_03 IN 0 TO 127 GENERATE
    Add1_add_cast(t_03) <= resize(Gain1_out1(t_03), 67);
    Add1_add_cast_1(t_03) <= resize(Add_out1(t_03) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 67);
    Add1_out1(t_03) <= Add1_add_cast(t_03) + Add1_add_cast_1(t_03);
  END GENERATE Add1_out1_gen;



  Gain2_out1_gen: FOR t_04 IN 0 TO 127 GENERATE
    Gain2_out1(t_04) <= resize(Add1_out1(t_04) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 134);
  END GENERATE Gain2_out1_gen;



  Add2_out1_gen: FOR t_05 IN 0 TO 127 GENERATE
    Add2_add_cast(t_05) <= resize(Add1_out1(t_05) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 135);
    Add2_add_cast_1(t_05) <= resize(Gain2_out1(t_05), 135);
    Add2_out1(t_05) <= Add2_add_cast(t_05) + Add2_add_cast_1(t_05);
  END GENERATE Add2_out1_gen;


  outputgen: FOR k IN 0 TO 127 GENERATE
    Out1(k) <= std_logic_vector(Add2_out1(k));
  END GENERATE;

END rtl;

